/**
 * scripts/generate-fcm-sw.js
 *
 * Generates public/firebase-messaging-sw.js by templating env vars into
 * the Firebase Messaging service worker.
 *
 * Why this is a build-time script instead of a static file:
 *   - SWs run outside the Next.js bundler, so they can't read
 *     process.env at request time.
 *   - Hardcoding env values in the committed SW makes key rotation
 *     a two-step change (env + source).
 *   - Letting the build inject them keeps env vars as the single
 *     source of truth, and works the same locally (predev hook) and
 *     on Vercel (prebuild hook).
 *
 * Runs automatically via the `predev` and `prebuild` scripts in
 * package.json. Safe to run by hand: `node scripts/generate-fcm-sw.js`.
 */
const fs = require('fs');
const path = require('path');

// Load .env.local locally; on Vercel the env vars are already in
// process.env so dotenv finds nothing to load and that's fine.
try { require('dotenv').config({ path: path.join(__dirname, '..', '.env.local') }); } catch {}

const REQUIRED = [
  'NEXT_PUBLIC_FIREBASE_API_KEY',
  'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
  'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
  'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  'NEXT_PUBLIC_FIREBASE_APP_ID',
];

const missing = REQUIRED.filter(k => !process.env[k]);
if (missing.length > 0) {
  console.warn(
    '[generate-fcm-sw] WARN: missing env vars: ' + missing.join(', ') +
    '. The generated SW will have empty config and push notifications ' +
    'will be a no-op. Set these in .env.local (local) or Vercel Project ' +
    'Settings → Environment Variables (production).'
  );
}

const cfg = {
  apiKey:            process.env.NEXT_PUBLIC_FIREBASE_API_KEY            || '',
  authDomain:        process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN        || '',
  projectId:         process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID         || '',
  storageBucket:     process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET     || '',
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID|| '',
  appId:             process.env.NEXT_PUBLIC_FIREBASE_APP_ID             || '',
};

const sw = `// public/firebase-messaging-sw.js
// AUTO-GENERATED by scripts/generate-fcm-sw.js — do not edit by hand.
// Regenerated on every \`npm run dev\` / \`npm run build\`.
//
// This service worker is what Google's FCM infrastructure looks for at
// /firebase-messaging-sw.js — its name + path are part of the FCM
// contract. It handles 'push' events when the page is closed and the
// 'notificationclick' event so tapping the chime opens the right page.
//
// Coexists with the main /sw.js (the PWA shell SW). Both register on
// the same origin under different scopes — modern browsers handle that
// fine, and FCM scopes itself to /firebase-cloud-messaging-push-scope.

importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(cfg, null, 2)});

const messaging = firebase.messaging();

// Background push — when the page is closed, this fires and we render
// the notification ourselves. We send DATA-ONLY messages from the
// Cloud Function so we control the title/body/icon/click target here
// (FCM's auto-render is harder to style consistently across browsers).
messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const title = data.title || 'HaloHelm';
  const body  = data.body  || '';
  const tag   = data.tag   || data.kind || 'halohelm';
  const url   = data.url   || '/admin/kitchen-new';

  self.registration.showNotification(title, {
    body,
    icon: '/icons/icon-192.png',
    badge: '/icons/icon-192.png',
    tag,
    renotify: true,
    requireInteraction: false,
    data: { url },
  });
});

// Click the notification → focus the right admin page if it's already
// open, else open a new tab. clientsClaim() isn't called here because
// our scope (/firebase-cloud-messaging-push-scope) doesn't manage page
// fetches; we just need it active for push events.
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || '/admin/kitchen-new';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((wins) => {
      const target = url.startsWith('http') ? url : (self.location.origin + url);
      for (const w of wins) {
        if (w.url.startsWith(self.location.origin) && 'focus' in w) {
          w.navigate(target);
          return w.focus();
        }
      }
      if (self.clients.openWindow) return self.clients.openWindow(target);
    })
  );
});
`;

const outPath = path.join(__dirname, '..', 'public', 'firebase-messaging-sw.js');
fs.writeFileSync(outPath, sw, 'utf8');
console.log('[generate-fcm-sw] wrote', path.relative(path.join(__dirname, '..'), outPath));
